#ifndef _GAMB_CONSTS
#define _GAMB_CONSTS

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define WINDOW_PADDING 8.0f
#define BLOCK_PADDING 4.0f

#define PLAYER_WIDTH 96.0f
#define PLAYER_HEIGHT 8.0f
#define PLAYER_PADDING 16.0f

#define BALL_WIDTH 8.0f
#define BALL_HEIGHT BALL_WIDTH
#define BALL_START_Y ((WINDOW_HEIGHT) - 64.0f)
#define BALL_INITIAL_SPEED 500.0f

#define NROWS 8
#define NCOLS 12
#define NBLOCKS 96

#define BLOCKS_TOP_PADDING 56.0f
#define BACKWALL_THICKNESS 6.0f

#define NUM_LIVES 3
#define LIVES_INDICATOR_DIM 28.0f
#define LIVES_INDICATOR_PADDING 4.0f

#define BUTTON_WIDTH 128
#define BUTTON_HEIGHT 48
#define BUTTON_PADDING 8

#endif // _GAMB_CONSTS
