#ifndef _GAMB_CONSTS
#define _GAMB_CONSTS

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define WINDOW_PADDING 4
#define BLOCK_PADDING 4

#define PLAYER_WIDTH 96
#define PLAYER_HEIGHT 8
#define PLAYER_PADDING 16

#define BALL_WIDTH 8
#define BALL_HEIGHT BALL_WIDTH
#define BALL_START_Y ((WINDOW_HEIGHT) - 64)
#define BALL_INITIAL_SPEED 500.0f

#define NROWS 8
#define NCOLS 12
#define NBLOCKS 96

#define BLOCKS_TOP_PADDING 56
#define BACKWALL_THICKNESS 6

#define GAME_FONT "assets/AldotheApache.ttf"

#endif // _GAMB_CONSTS
